### ISSUE TITLE
Creating multiple disks?

### ISSUE THREAD

**Issue by rkulagowski** [AerisCloud/ansible-disk#11]
If I want to use the module against multiple disks, how do I do that?

In my group_vars, I've got:

```
disk_additional_disks:
- disk: /dev/xvdf
  fstype: ext4
  opts: "-m 1"
  mount_options: defaults
  mount: /mnt/tmp
- disk: /dev/xvdg
  fstype: ext4
  opts: "-m 1"
  mount_options: defaults
  mount: /mnt/tmp2
```

But it's only executing against /dev/xvdf
