### ISSUE TITLE
No longer works with Azure

### ISSUE THREAD

**Issue by ellispritchard** [AerisCloud/ansible-disk#18]
`_nvme_ioctl IOError: [Errno 22] Invalid argument` when attempting to attach Azure disk.

Version @ e303c7fb7634cfc0831c80fb0210026eb096bfac works fine, version @ c0ac6978d715b461fbf20aca719cd5196bc60645 (current master) fails.

```
fatal: [bk-test-vm1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to bk-test-vm1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/agrimetrics/.ansible/tmp/ansible-tmp-1545234609.6925719-280473579861797/AnsiballZ_disk_config.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/agrimetrics/.ansible/tmp/ansible-tmp-1545234609.6925719-280473579861797/AnsiballZ_disk_config.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/agrimetrics/.ansible/tmp/ansible-tmp-1545234609.6925719-280473579861797/AnsiballZ_disk_config.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_disk_config_payload_BSZXKz/__main__.py\", line 180, in <module>\r\n  File \"/tmp/ansible_disk_config_payload_BSZXKz/__main__.py\", line 164, in main\r\n  File \"/tmp/ansible_disk_config_payload_BSZXKz/__main__.py\", line 99, in __init__\r\n  File \"/tmp/ansible_disk_config_payload_BSZXKz/__main__.py\", line112, in ctrl_identify\r\n  File \"/tmp/ansible_disk_config_payload_BSZXKz/__main__.py\", line 108, in _nvme_ioctl\r\nIOError: [Errno 22] Invalid argument\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by MiLk** [comment]
Could you try to set `disk_discover_aws_nvme_ebs` to false in you inventory?

**Comment by ellispritchard** [comment]
Hi; this had no effect (adding `disk_discover_aws_nvme_ebs: false` to the `disk_additional_disks` config in `group_vars`) , however commenting out the "Discover NVMe EBS" lines from the role code allowed it to succeed, so perhaps it's not picking this option up correctly?

My `group_vars` has: 

```
disk_additional_disks:
 - disk: /dev/sdc
   fstype: ext4
   mount_options: "defaults,nofail"
   mount: /opt/docker
   user: root
   group: root
   disk_discover_aws_nvme_ebs: false
   disable_periodic_fsck: false
```

**Comment by ellispritchard** [comment]
Ah, of course, this needs to be set at the top-level, not within `disk_additonal_disks`; thus:

```
disk_discover_aws_nvme_ebs: false
disk_additional_disks:
 - disk: /dev/sdc
   fstype: ext4
   mount_options: "defaults,nofail"
   mount: /opt/docker
   user: root
   group: root
   disable_periodic_fsck: false
```
this works. 👍
